config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: "user/registrations" 
  }
  namespace :admin do
    resources :users
    resources :products
    resources :orders,only: [:index]
  end

  resources :users, only: [:show]

  # namespace :users do
  #   resources :products, :catagories, :subcatagories     
  # end

  namespace :catagories do
    namespace :subcatagories do
      resources :products, only: [:index,:show]
      resources :comments
      resources :likes
    end
  end

  resources :myproducts, only: [:index,:show]
  resources :catagories
  resources :subcatagories do
    member do
      get :get_subcategory
    end  
  end
  resources :states,only: [:index]
  resources :cities,only: [:index]

  resources :carts,only: [:show]
  resources :cart_products,only: [:create,:destroy,:show] do
    member do
      post :add_quantity
      post :reduce_quantity
    end
  end
  resources :orders
  
  get 'admin_dashboard/index'
  get 'admin_dashboard/show'

  get 'home/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"

end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
##########################################################

    has_many :products_subcatagories
    has_many :subcatagories, through: :products_subcatagories

#################################################
    has_many :cart_products
    has_many :carts, through: :cart_products
    has_many :orderproducts
    has_many :orders, through: :orderproducts
    
#####################################################
    has_many :comments
    has_many :likes

    has_many :images, as: :imageable, dependent: :destroy

    mount_uploaders :images, ProfilePicUploader

    validates :name,:price, presence: true
    validates :name, uniqueness: true 

    enum status: {pending: 0, active: 1}

    # {message: "Subcatagory must include. Don't worry if you do not have subcatagory 
    #     click #{ link_to 'new subcatagories', new_users_subcatagory_path } "}
    
    scope :search, -> (query) {where("lower(name) LIKE ?","%"+ query +"%")}
end

app/models/subcatagory.rb
class Subcatagory < ApplicationRecord
    has_many :products_subcatagories
    has_many :products, through: :products_subcatagories

    belongs_to :catagory
    belongs_to :user
    

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    load_and_authorize_resource
    include ConcernHelper
    
    def index
        find_admin_seller_product
    end

    def show
        @product=Product.find(params[:id])
    end

    def new
        @product =Product.new
    end

    def edit
        @product=Product.find(params[:id])
    end
    
    def create
        @product =Product.new(product_params)
        if @product.save
            @subcatagory=params[:product][:subcatagory_ids].reject(&:blank?)
            @subcatagory.each do |subcatagory|
                ProductsSubcatagory.create!(product_id: @product.id ,subcatagory_id: subcatagory)
            end
            
            redirect_to myproduct_path(@product)
        else
            render 'new'
        end

    end

    def update
        @product= Product.find(params[:id])
        if @product.update(product_params)
            redirect_to myproduct_path(@product)
        else
            render 'edit'
        end
        
    end
    
    def destroy
        @product=Product.find(params[:id])
        @product.destroy
        redirect_to myproducts_path 
        
    end
    
    private
    def product_params
        params.require(:product).permit(:name, :price, :user_id,{images: []} )
    end

end

app/controllers/catagories/subcatagories/comments_controller.rb
class Catagories::Subcatagories::CommentsController < ApplicationController
    load_and_authorize_resource
    def create
        @comment = Comment.new(comment_params)
        @product=@comment.product
        if @comment.save 
            respond_to do |format|
                format.js   {}
                format.json { render json: @comment, status: :created, location: @comment }
            end
        end
    end

    def edit
        @product=@comment.product
        respond_to do |format|
            format.js
          end
    end

    def destroy
        @comment = Comment.find(params[:id])
        if @comment.destroy
            respond_to do |format|
                format.js   { render :layout => false }
            end 
        end
        
    end

    def update
        @comments = Comment.find(params[:id])
        @product=@comment.product
        respond_to do |format|
        if @comment.update(comment_params)
          format.js { render :layout => false }
        else
          format.js
        end
        end
      end
     
    private
    def comment_params
        params.require(:comment).permit(:body, :user_id, :product_id, :score )
    end

end

app/controllers/catagories/subcatagories/likes_controller.rb
class Catagories::Subcatagories::LikesController < ApplicationController
    def create
        # debugger
        @like=Like.create(like_params)
        @like.save

        if already_liked?
            @like = Like.find(params[:id])
            @like.destroy
        else
            @product.likes.create(like_params)
        end
        redirect_to catagories_subcatagories_product_path(@like.product_id)
        
    end

    # def destroy
    #     if !(already_liked)?
    #         flash[:notice]="already liked"
    #     else
    #         @product=Product.find_by(params[:id])
    #         @like=@product.likes.find(:id)
    #         @like.destroy
            
    #     end
    #     redirect_to catagories_subcatagories_product_path
        
    # end

    private
    def like_params
        params.permit(:user_id, :product_id)
    end

    def already_liked?
        Like.where(user_id: current_user.id,product_id: params[:product_id]).exists?
    end
end

app/controllers/catagories/subcatagories/products_controller.rb
class Catagories::Subcatagories::ProductsController < ApplicationController
    # skip_before_action :authenticate_user!, only: [:index,:show]
    load_and_authorize_resource
    include FindProduct

    def index
        find_product
    end

    def show
        @product=Product.find(params[:id])
        @comment=Comment.new
    end

    private
    def product_params
        params.require(:product).permit(:name, :price, :user_id,:subcatagory_id)
    end

end

app/controllers/products_controller.rb
# class ProductsController < ApplicationController
#     def index
#         @products = Product.all
#         @products = Product.includes(:user)
#     end
#     def show
#         @product=Product.find(params[:id])
#     end

#     def new
#         @product =Product.new
#     end

#     def edit
#         @product=Product.find(params[:id])
#     end
  
#     def create
#         @product =Product.new(product_params)
#         if @product.save
#             redirect_to @product
#         else
#             render 'new'
#         end

#     end

#     def update
#         @product= Product.find(params[:id])
#         if @product.update(product_params)
#             redirect_to @product
#         else
#             render 'edit'
#         end
       
#     end
#     def destroy
#         @product=Product.find(params[:id])
#         @product.destroy
#         redirect_to products_path 
        
#     end
    
#     private
#     def product_params
#         params.require(:product).permit(:name, :price, :user_id)
#     end
# end

app/controllers/subcatagories_controller.rb
class SubcatagoriesController < ApplicationController
    load_and_authorize_resource :except => [:get_subcategory]
    
    def index
        @subcatagories=Subcatagory.all
    end

    def get_subcategory
        @catagory=Catagory.find(params[:id])
        @subcatagories=@catagory.subcatagories
        respond_to do |format|
            format.js { render :layout => false }
        end
    end
    def show
        @subcatagory=Subcatagory.find(params[:id])
    end

    def new
        @subcatagory =Subcatagory.new
    end

    def edit
        @subcatagory=Subcatagory.find(params[:id])
    end
  
    def create
        @subcatagory =Subcatagory.new(subcatagory_params)
        if @subcatagory.save
            redirect_to subcatagory_path(@subcatagory)
        else
            render 'new'
        end

    end

    def update
        @subcatagory= Subcatagory.find(params[:id])
        if @subcatagory.update(subcatagory_params)
            redirect_to subcatagory_path(@subcatagory)
        else
            render 'edit'
        end
       
    end
    def destroy
        @subcatagory=Subcatagory.find(params[:id])
        @subcatagory.destroy
        redirect_to subcatagories_path 
        
    end
    
    private
    def subcatagory_params
        params.require(:subcatagory).permit(:name,:user_id,:catagory_id)
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
    def options_for_catagory
        Catagory.all.collect { |m| [m.name,m.id]}
    end
end

app/helpers/catagories/subcatagories/comments_helper.rb
module Catagories::Subcatagories::CommentsHelper
    
    def create_update
        if @comment.id != nil
            return "/catagories/subcatagories/comments/#{@comment.id}"
        else
            return catagories_subcatagories_comments_path
        end

    end
    def method
        if @comment.id != nil
            return :patch
        else
            return :post
        end

    end
end

app/helpers/catagories/subcatagories/likes_helper.rb
module Catagories::Subcatagories::LikesHelper
end

app/helpers/catagories/subcatagories/products_helper.rb
module Catagories::Subcatagories::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
    def options_for_subcatagory
      Subcatagory.all.collect { |m| [m.name,m.id]}
    end
    def options_for_catagory
      Catagory.all.collect { |m| [m.name,m.id]}
    end
end

app/helpers/subcatagories_helper.rb
module SubcatagoriesHelper
    def options_for_catagory
       Catagory.all.collect { |m| [m.name,m.id]}
    end
end

app/views/catagories/subcatagories/products/_form.html.erb
<%= form_for [:users, @product] do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        this product from being saved:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :user_id, value: current_user.id%>
  <%= f.text_field :name, placeholder: "Name of Product" %>
  <%= f.number_field :price, placeholder: "price" %>
  <%= f.label :select_catagory %>
  <%= f.select :subcatagory_id, options_for_subcatagory,:prompt => 'Select One' %>
  <%= f.submit "Submit" %>
<% end %>

app/views/catagories/subcatagories/products/_index.html.erb
  <div class="row row-cols-1 row-cols-md-3 g-4 py-5 px-5" style="margin-left: 200px;" >
    <% @products.each do |product| %>
      <div class="col">
        <div class="card h-100">
            <% if product.images.present? %>
              <%= link_to image_tag(product.images[0].url ,class:'card-img-top'),catagories_subcatagories_product_path(product) %>
            <% end %>
            
          <div class="card-body">
            <h5 class="card-title"><%= link_to product.name,catagories_subcatagories_product_path(product) %></h5>
            <small><%= product.price %></small>
            <p class="card-text">This lead-in to additional content. This content is a little bit longer.</p>
          </div>
          <% if user_signed_in? && current_user.admin? %>
            <div class="card-footer">  
              <%= link_to 'Show', catagories_subcatagories_product_path(product) ,class:"btn btn-primary" %>
              <%= link_to 'edit', edit_admin_product_path(product), class:"btn btn-primary"  %>
              <%= link_to 'remove', myproduct_path(product), method: :delete,
              data: { confirm: 'Are you sure?' },class:"btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>  

app/views/catagories/subcatagories/products/edit.html.erb
 <h1>Update product</h1>


<div>
   <%= render 'form' %>
 </div>

app/views/catagories/subcatagories/products/index.html.erb
<%= render 'index' %>

app/views/catagories/subcatagories/products/new.html.erb
 <h1>New product</h1>


<div>
   <%= render 'form' %>
 </div>

app/views/catagories/subcatagories/products/show.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>
<%= link_to 'my products', myproducts_path %>
<div claass='container' >
  <div class="row row-cols-1 row-cols-md-2 g-4 py-5 px-5" >
    <div class='col'>
      <% if @product.images.present? %>
        <%= image_tag @product.images[0].url ,style:'width:200px' %>
      <% end %>
    </div>
    <div class='col'>
      <div>
        <h5><%= @product.name %></h5>
      </div>
      <div>
        <p><%= @product.price %></p>
      </div>
      <div>
        <p><%= @product.user.first_name %></p>
      </div>
      <% if user_signed_in? %>
        <%= link_to catagories_subcatagories_likes_path(product_id: @product.id,
        user_id: current_user.id), method: :post do %>
          <i class='far fa-thumbs-up' id='Liked'></i>
        <% end %>        
      <% end %>



        <br />
        <% @product.subcatagories.each do |subcatagory| %>
            <%= subcatagory.name %>
        <% end %>
      <div id='add_cart'>
      <button type="button" class="btn bg-transparent btn-lg border-primary rounded-pill " value='1' >Add To Cart</button>
      </div>

    <div>
    </div>
  </div>
</div>
<% if @product.user != current_user || current_user.admin? %>
<div class="commentsform" id='commentForm' >
   <%= render 'catagories/subcatagories/comments/form' %>
</div>   
<% end %>

<div id='commentdiv' >
   <%= render 'catagories/subcatagories/comments/comment' %>  
</div>



<!-- Modal -->
<div class="modal fade" id="cartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Conratulation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p> Product added to cart seccussffuly.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= link_to "Show", cart_path(current_user.cart), :class=> "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

<script>
    $(document).ready(function () {
        var like_value=$("#Like").value;
        console.log(like_value);
        $("#Like").on("click" ,function(e) {
            var btn_press= $(this).html();
            console.log(btn_press);
        });
          $('.rounded-pill').click(function() {
              $('.rounded-pill').attr("disabled", "disabled"); // disable button
              window.setTimeout(function() {
                $('.rounded-pill').removeAttr("disabled"); // enable button
              }, 200 /* 2 sec */); 
          });
        $(".rounded-pill").on("click" ,function(e) {
          var btn_press= $(this).html();
            var product_id = <%= @product.id %>
            var product_user = <%= @product.user.id %>
            var current_user = <%= current_user.id %>
            if (product_user === current_user) {
              alert("Please Stop You are the owner of the Product")
            } else {
            $.ajax({
              type:"post",
              url:"/cart_products?product_id="+product_id
            });              
            }

        });

    });

</script>