config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: "user/registrations" 
  }
  namespace :admin do
    resources :users
    resources :products
    resources :orders,only: [:index]
  end

  resources :users, only: [:show]

  # namespace :users do
  #   resources :products, :catagories, :subcatagories     
  # end

  namespace :catagories do
    namespace :subcatagories do
      resources :products, only: [:index,:show]
      resources :comments
      resources :likes
    end
  end

  resources :myproducts, only: [:index,:show]
  resources :catagories
  resources :subcatagories do
    member do
      get :get_subcategory
    end  
  end
  resources :states,only: [:index]
  resources :cities,only: [:index]

  resources :carts,only: [:show]
  resources :cart_products,only: [:create,:destroy,:show] do
    member do
      post :add_quantity
      post :reduce_quantity
    end
  end
  resources :orders
  
  get 'admin_dashboard/index'
  get 'admin_dashboard/show'

  get 'home/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new  #non-logged-in user

      if user.id? and user.is? :admin
        can :manage, :all

      elsif user.id? and user.is? :customer

        can [ :update, :destroy ], Comment do |comment|
          comment.user_id == user.id
        end

        can :read, Product
        can :show, User
        can [:read,:create], Comment
        can [:read],Cart, user_id: user.id
        can [:read,:create,:update,:destroy],Order,user_id: user.id
        can [:read,:create,:update,:destroy,:add_quantity,:reduce_quantity],CartProduct

      elsif user.id? and user.is? :seller
        can [:update, :destroy,:create], Product, :user_id => user.id
        can :read, Product
        can :show, User
        can :read,:myproducts
        can :read, Catagory
        can [:read,:get_subcategory], Subcatagory
        can :read,:admin_dashboard
        can :read ,Cart,user_id: user.id
        can [:read,:create], Comment
        can [:read,:create,:update,:destroy,:add_quantity,:reduce_quantity],CartProduct
        can :read, Product
        can :read,Order, user_id: user.id
      else
        can :read, Product
        can :read, Comment
      end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_products, dependent: :destroy
    has_many :products, through: :cart_products
    belongs_to :user

    def sub_total
      @cart_product = CartProduct.joins(:product).where(cart_id: self.id)
      return @cart_product.map(&:total_price).reduce(:+)
    end
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
    belongs_to :product
    belongs_to :cart 
    
    def total_price
        self.quantity * self.product.price
    end
end

app/models/catagory.rb
class Catagory < ApplicationRecord
    has_many :subcatagories
    belongs_to :user, optional: true


end

app/models/city.rb
class City < ApplicationRecord
    belongs_to :country, :class_name => "country",
    :foreign_key => "country_id"
    belongs_to :state, :class_name => "state",
    :foreign_key => "state_id"
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :product
end

app/models/country.rb
class Country < ApplicationRecord
    has_many :states
    has_many :cities
    has_many :users
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :orderproducts, dependent: :destroy
    has_many :products, through: :orderproducts
    belongs_to :user
    
    def sub_total
        @order_product = Orderproduct.joins(:product).where(order_id: self.id)
        return @order_product.map(&:total_price).reduce(:+)
    end
    
    scope :seller_products, -> {joins(:orderproducts).where(:orderproducts => {:product_id => @product.ids})}

end

app/models/orderproduct.rb
class Orderproduct < ApplicationRecord
    belongs_to :order
    belongs_to :product

    def total_price
        self.quantity.to_i * self.product.price
    end
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
##########################################################

    has_many :products_subcatagories
    has_many :subcatagories, through: :products_subcatagories

#################################################
    has_many :cart_products
    has_many :carts, through: :cart_products
    has_many :orderproducts
    has_many :orders, through: :orderproducts
    
#####################################################
    has_many :comments
    has_many :likes

    has_many :images, as: :imageable, dependent: :destroy

    mount_uploaders :images, ProfilePicUploader

    validates :name,:price, presence: true
    validates :name, uniqueness: true 

    enum status: {pending: 0, active: 1}

    # {message: "Subcatagory must include. Don't worry if you do not have subcatagory 
    #     click #{ link_to 'new subcatagories', new_users_subcatagory_path } "}
    
    scope :search, -> (query) {where("lower(name) LIKE ?","%"+ query +"%")}
end

app/models/state.rb
class State < ApplicationRecord
    belongs_to :country, :class_name => "country",
    :foreign_key => "country_id"
    has_many :cities
    has_many :users
end

app/models/subcatagory.rb
class Subcatagory < ApplicationRecord
    has_many :products_subcatagories
    has_many :products, through: :products_subcatagories

    belongs_to :catagory
    belongs_to :user
    

end

app/models/user.rb
class User < ApplicationRecord

  after_create :create_user_cart
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :image, as: :imageable, dependent: :destroy
  mount_uploader :image, ProfilePicUploader
  # validates_integrity_of  :profile_pic
  # validates_processing_of :profile_pic
  enum role: {customer: 0,seller: 1, admin: 2}
  enum status: {pending: 0, active: 1}


  has_many :comments
  has_many :likes
  has_many :products
  has_many :catagories
  has_many :subcatagories
  belongs_to :country
  belongs_to :state
  belongs_to :city
  has_one :cart
  has_many :orders, dependent: :destroy


  def create_user_cart
      @current_cart=Cart.create(user_id: self.id)
  end

  def is?( requested_role )
    self.role == requested_role.to_s
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_header.html.erb
<div class="container-fluid" style="background: linear-gradient(90deg, #707AE7 33.334%, #F1F6F7 30%),#F1F6F7;" >
  <div class="row no-gutters align-items-center pt-60px">
    <div class="col-5 d-none d-sm-block " >
       
       <%= image_tag "shoping_cart.png", style:"width:270px;margin-left: 180px !important;" ,class:"mt-4" %>
    </div>
    <div class="col-sm-7 col-lg-6 m-5" >
      <h4>Shop is fun</h4>
      <h1>Browse Our Premium Product</h1>
      <p>Us which over of signs divide dominion deep fill bring they're meat beho
       upon own earth without mo
      rning over third. Their male dry. They are great appear whose land fly grass.</p>
    </div>
  </div>
</div>

app/views/shared/_navebar.html.erb
  <!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!-- Container wrapper -->
  <div class="container">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
      data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
      aria-expanded="false" id="#manue"
      aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-3">
        <li class="nav-item">
          <a class="nav-link active d-flex align-items-center" aria-current="page" href="#"><i
              class="fas fa-bars pe-2"></i>Menu</a>
        </li>
      </ul>
      <form class="d-flex align-items-center w-100 form-search" action="/catagories/subcatagories/products" >
        <div class="input-group">
          <button class="btn btn-light dropdown-toggle shadow-0" type="button" data-bs-toggle="dropdown"
            aria-expanded="false" style="padding-bottom: 0.4rem;">All
          </button>
          <ul class="dropdown-menu dropdown-menu-dark fa-ul">
              <% Subcatagory.all.each do |subcategory| %>
               <li>
                <%= link_to subcategory.name, catagories_subcatagories_products_path(subcatagory: subcategory.id),
                class:"dropdown-item"  %>
               </li>
              <% end %>
            <li>
              <%= link_to 'All', catagories_subcatagories_products_path, class:"dropdown-item" %>
            </li>
          </ul>
          <input type="search" class="form-control" placeholder="Search" id="search" name="q" aria-label="Search" >
          <button class="btn btn-primary" type="submit"><i class="fas fa-search ps-3"></i></button>
        </div>
      </form>
      <ul class="navbar-nav ms-3">
      <% if user_signed_in? %>
        <li class="nav-item me-3">
           <%= link_to cart_path(current_user.cart), :class=> "nav-link d-flex align-items-center me-3" do %>
             <i class="fas fa-shopping-cart" aria-hidden="true" target="_blank"></i>
           <% end %>
        </li>
      <% end %>
        <li class="nav-item px-1 mx-1">
          <% if user_signed_in? %>
            <% if current_user.admin? || current_user.seller? %>
              <%= link_to "DASHBOARD",admin_dashboard_index_path,class:"nav nav-link" %>
            <% else %>
            <div class="dropdown">
              <button class="btn dropdown-toggle shadow-0" type="button" data-bs-toggle="dropdown" id="dropdownMenuButton2"
                aria-expanded="false" style="padding-bottom: 0.4rem; color:white;">
                <%# <i class="fa fa-user"></i> %>
                my account
              </button>
              <ul class="dropdown-menu dropdown-menu-dark fa-ul" aria-labelledby="dropdownMenuButton2" >
                <li>
                  <strong class="dropdown-item active"><%= current_user.first_name %></strong>
                </li>
                <li>
                <%= link_to 'My profile', user_path(current_user) , class:"dropdown-item nav-link d-flex align-items-center" %>
                </li>
                <li>
                <%= link_to 'My Orders', orders_path , class:"dropdown-item nav-link d-flex align-items-center" %>
                </li>
              </ul>  
            <% end %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path,class:"nav-link d-flex align-items-center mx-1"  %>
          <% end %>
          </li>
          <li class="nav-item">
            <% if user_signed_in? %>
            <%= button_to "Logout", destroy_user_session_path,method: :delete, 
            class:"nav-link d-flex align-items-center bg-transparent border-0" %>
          </li>
          <li class="nav-item">
            <% else %>
              
              <%= link_to "Login", new_user_session_path,class:"nav-link d-flex align-items-center"  %>
          <% end %>
        </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

<script>
    $(document).ready(function () {
        $(".manue").on("click" ,function(e) {

        });

        $("#searchk").on("change",function (e) {
          console.log(this);
          $.ajax ({
            type: "get",
            url: "/catagories/subcatagories/products"
          });
        });
    });

</script>

app/views/shared/_notifecation.html.erb
  <% if notice %>
    <p class="alert alert-success text-center"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger text-center"><%= alert %></p>
  <% end %>