config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: "user/registrations" 
  }
  namespace :admin do
    resources :users
    resources :products
    resources :orders,only: [:index]
  end

  resources :users, only: [:show]

  # namespace :users do
  #   resources :products, :catagories, :subcatagories     
  # end

  namespace :catagories do
    namespace :subcatagories do
      resources :products, only: [:index,:show]
      resources :comments
      resources :likes
    end
  end

  resources :myproducts, only: [:index,:show]
  resources :catagories
  resources :subcatagories do
    member do
      get :get_subcategory
    end  
  end
  resources :states,only: [:index]
  resources :cities,only: [:index]

  resources :carts,only: [:show]
  resources :cart_products,only: [:create,:destroy,:show] do
    member do
      post :add_quantity
      post :reduce_quantity
    end
  end
  resources :orders
  
  get 'admin_dashboard/index'
  get 'admin_dashboard/show'

  get 'home/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"

end

app/models/subcatagory.rb
class Subcatagory < ApplicationRecord
    has_many :products_subcatagories
    has_many :products, through: :products_subcatagories

    belongs_to :catagory
    belongs_to :user
    

end

app/controllers/catagories/subcatagories/comments_controller.rb
class Catagories::Subcatagories::CommentsController < ApplicationController
    load_and_authorize_resource
    def create
        @comment = Comment.new(comment_params)
        @product=@comment.product
        if @comment.save 
            respond_to do |format|
                format.js   {}
                format.json { render json: @comment, status: :created, location: @comment }
            end
        end
    end

    def edit
        @product=@comment.product
        respond_to do |format|
            format.js
          end
    end

    def destroy
        @comment = Comment.find(params[:id])
        if @comment.destroy
            respond_to do |format|
                format.js   { render :layout => false }
            end 
        end
        
    end

    def update
        @comments = Comment.find(params[:id])
        @product=@comment.product
        respond_to do |format|
        if @comment.update(comment_params)
          format.js { render :layout => false }
        else
          format.js
        end
        end
      end
     
    private
    def comment_params
        params.require(:comment).permit(:body, :user_id, :product_id, :score )
    end

end

app/controllers/catagories/subcatagories/likes_controller.rb
class Catagories::Subcatagories::LikesController < ApplicationController
    def create
        # debugger
        @like=Like.create(like_params)
        @like.save

        if already_liked?
            @like = Like.find(params[:id])
            @like.destroy
        else
            @product.likes.create(like_params)
        end
        redirect_to catagories_subcatagories_product_path(@like.product_id)
        
    end

    # def destroy
    #     if !(already_liked)?
    #         flash[:notice]="already liked"
    #     else
    #         @product=Product.find_by(params[:id])
    #         @like=@product.likes.find(:id)
    #         @like.destroy
            
    #     end
    #     redirect_to catagories_subcatagories_product_path
        
    # end

    private
    def like_params
        params.permit(:user_id, :product_id)
    end

    def already_liked?
        Like.where(user_id: current_user.id,product_id: params[:product_id]).exists?
    end
end

app/controllers/catagories/subcatagories/products_controller.rb
class Catagories::Subcatagories::ProductsController < ApplicationController
    # skip_before_action :authenticate_user!, only: [:index,:show]
    load_and_authorize_resource
    include FindProduct

    def index
        find_product
    end

    def show
        @product=Product.find(params[:id])
        @comment=Comment.new
    end

    private
    def product_params
        params.require(:product).permit(:name, :price, :user_id,:subcatagory_id)
    end

end

app/controllers/subcatagories_controller.rb
class SubcatagoriesController < ApplicationController
    load_and_authorize_resource :except => [:get_subcategory]
    
    def index
        @subcatagories=Subcatagory.all
    end

    def get_subcategory
        @catagory=Catagory.find(params[:id])
        @subcatagories=@catagory.subcatagories
        respond_to do |format|
            format.js { render :layout => false }
        end
    end
    def show
        @subcatagory=Subcatagory.find(params[:id])
    end

    def new
        @subcatagory =Subcatagory.new
    end

    def edit
        @subcatagory=Subcatagory.find(params[:id])
    end
  
    def create
        @subcatagory =Subcatagory.new(subcatagory_params)
        if @subcatagory.save
            redirect_to subcatagory_path(@subcatagory)
        else
            render 'new'
        end

    end

    def update
        @subcatagory= Subcatagory.find(params[:id])
        if @subcatagory.update(subcatagory_params)
            redirect_to subcatagory_path(@subcatagory)
        else
            render 'edit'
        end
       
    end
    def destroy
        @subcatagory=Subcatagory.find(params[:id])
        @subcatagory.destroy
        redirect_to subcatagories_path 
        
    end
    
    private
    def subcatagory_params
        params.require(:subcatagory).permit(:name,:user_id,:catagory_id)
    end
end

app/helpers/catagories/subcatagories/comments_helper.rb
module Catagories::Subcatagories::CommentsHelper
    
    def create_update
        if @comment.id != nil
            return "/catagories/subcatagories/comments/#{@comment.id}"
        else
            return catagories_subcatagories_comments_path
        end

    end
    def method
        if @comment.id != nil
            return :patch
        else
            return :post
        end

    end
end

app/helpers/catagories/subcatagories/likes_helper.rb
module Catagories::Subcatagories::LikesHelper
end

app/helpers/catagories/subcatagories/products_helper.rb
module Catagories::Subcatagories::ProductsHelper
end

app/helpers/subcatagories_helper.rb
module SubcatagoriesHelper
    def options_for_catagory
       Catagory.all.collect { |m| [m.name,m.id]}
    end
end

app/views/subcatagories/_form.html.erb
<%= form_for @subcatagory do |f| %>
  <% if @subcatagory.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@subcatagory.errors.count, "error") %> prohibited
        this subcatagory from being saved:
      </h2>
      <ul>
        <% @subcatagory.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :user_id, value: current_user.id%>
  <%= f.hidden_field :catagory_id, value:'' %>
  <%= f.text_field :name %>
  <%= f.select :catagory_id, options_for_catagory,:prompt => 'Select One' %>  
  <%= f.submit "Submit" %>
<% end %>

app/views/subcatagories/edit.html.erb
 <h1>Update catagory</h1>


<div>
   <%= render 'form' %>
 </div>

app/views/subcatagories/get_subcategory.js.erb
$(".label").html("<label class='p-1' >Select Subcategory<label> ")
$("#select_subcatagory").html(`<%= options_from_collection_for_select(@subcatagories, "id", "name") %>`);

app/views/subcatagories/index.html.erb
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
<div class="m-3">
  <table id="subcatagory-datatable" class="order-column cell-border row-border stripe table-bordered" data-source="<%= catagories_path(format: :json) %>">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Category</th>
        <th>Show</th>
        <th>edit</th>
        <th>remove</th>
      </tr>
    </thead>
    <tbody>
      <% @subcatagories.each do |subcatagory| %>
        <tr class="table-info hover">
          <td><%= subcatagory.id %></td>
          <td><%= subcatagory.name %></td>
          <td><%= subcatagory.catagory.name %></td>
          <td><%= link_to 'Show', subcatagory_path(subcatagory) %></td>
          <td><%= link_to 'edit', edit_subcatagory_path(subcatagory) %></td>
          <td><%= link_to 'remove', subcatagory_path(subcatagory), method: :delete, data: { confirm: 'Are you sure?' } %></td>        
          
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>

<script>
  $(window).on('load', function() {
    var t = $('#subcatagory-datatable').DataTable();
    $("body").css("background-color","#5BB9B8");
  });
</script>

app/views/subcatagories/new.html.erb
 <h1>New Subcatagory</h1>


<div>
   <%= render 'form' %>
 </div>

app/views/subcatagories/show.html.erb
<%= link_to 'all Subcatagories', subcatagories_path %>
<div>
<h5><%= @subcatagory.name %></h5>
</div>


<div>
<h5><%= @subcatagory.user.first_name %></h5>
</div>

<% @subcatagory.products.each do |product| %>
<%= product.name %>
<% end %>