config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: "user/registrations" 
  }
  namespace :admin do
    resources :users
    resources :products
    resources :orders,only: [:index]
  end

  resources :users, only: [:show]

  # namespace :users do
  #   resources :products, :catagories, :subcatagories     
  # end

  namespace :catagories do
    namespace :subcatagories do
      resources :products, only: [:index,:show]
      resources :comments
      resources :likes
    end
  end

  resources :myproducts, only: [:index,:show]
  resources :catagories
  resources :subcatagories do
    member do
      get :get_subcategory
    end  
  end
  resources :states,only: [:index]
  resources :cities,only: [:index]

  resources :carts,only: [:show]
  resources :cart_products,only: [:create,:destroy,:show] do
    member do
      post :add_quantity
      post :reduce_quantity
    end
  end
  resources :orders
  
  get 'admin_dashboard/index'
  get 'admin_dashboard/show'

  get 'home/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"

end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
##########################################################

    has_many :products_subcatagories
    has_many :subcatagories, through: :products_subcatagories

#################################################
    has_many :cart_products
    has_many :carts, through: :cart_products
    has_many :orderproducts
    has_many :orders, through: :orderproducts
    
#####################################################
    has_many :comments
    has_many :likes

    has_many :images, as: :imageable, dependent: :destroy

    mount_uploaders :images, ProfilePicUploader

    validates :name,:price, presence: true
    validates :name, uniqueness: true 

    enum status: {pending: 0, active: 1}

    # {message: "Subcatagory must include. Don't worry if you do not have subcatagory 
    #     click #{ link_to 'new subcatagories', new_users_subcatagory_path } "}
    
    scope :search, -> (query) {where("lower(name) LIKE ?","%"+ query +"%")}
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    load_and_authorize_resource
    include ConcernHelper
    
    def index
        find_admin_seller_product
    end

    def show
        @product=Product.find(params[:id])
    end

    def new
        @product =Product.new
    end

    def edit
        @product=Product.find(params[:id])
    end
    
    def create
        @product =Product.new(product_params)
        if @product.save
            @subcatagory=params[:product][:subcatagory_ids].reject(&:blank?)
            @subcatagory.each do |subcatagory|
                ProductsSubcatagory.create!(product_id: @product.id ,subcatagory_id: subcatagory)
            end
            
            redirect_to myproduct_path(@product)
        else
            render 'new'
        end

    end

    def update
        @product= Product.find(params[:id])
        if @product.update(product_params)
            redirect_to myproduct_path(@product)
        else
            render 'edit'
        end
        
    end
    
    def destroy
        @product=Product.find(params[:id])
        @product.destroy
        redirect_to myproducts_path 
        
    end
    
    private
    def product_params
        params.require(:product).permit(:name, :price, :user_id,{images: []} )
    end

end

app/controllers/catagories/subcatagories/products_controller.rb
class Catagories::Subcatagories::ProductsController < ApplicationController
    # skip_before_action :authenticate_user!, only: [:index,:show]
    load_and_authorize_resource
    include FindProduct

    def index
        find_product
    end

    def show
        @product=Product.find(params[:id])
        @comment=Comment.new
    end

    private
    def product_params
        params.require(:product).permit(:name, :price, :user_id,:subcatagory_id)
    end

end

app/controllers/products_controller.rb
# class ProductsController < ApplicationController
#     def index
#         @products = Product.all
#         @products = Product.includes(:user)
#     end
#     def show
#         @product=Product.find(params[:id])
#     end

#     def new
#         @product =Product.new
#     end

#     def edit
#         @product=Product.find(params[:id])
#     end
  
#     def create
#         @product =Product.new(product_params)
#         if @product.save
#             redirect_to @product
#         else
#             render 'new'
#         end

#     end

#     def update
#         @product= Product.find(params[:id])
#         if @product.update(product_params)
#             redirect_to @product
#         else
#             render 'edit'
#         end
       
#     end
#     def destroy
#         @product=Product.find(params[:id])
#         @product.destroy
#         redirect_to products_path 
        
#     end
    
#     private
#     def product_params
#         params.require(:product).permit(:name, :price, :user_id)
#     end
# end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
    def options_for_catagory
        Catagory.all.collect { |m| [m.name,m.id]}
    end
end

app/helpers/catagories/subcatagories/products_helper.rb
module Catagories::Subcatagories::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
    def options_for_subcatagory
      Subcatagory.all.collect { |m| [m.name,m.id]}
    end
    def options_for_catagory
      Catagory.all.collect { |m| [m.name,m.id]}
    end
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product] do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        this product from being saved:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <div class="m-4" >
      <%= f.label :name_Of_Product,class:"p-1" %>
      <%= f.text_field :name %>
    </div>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id%>
  <div class="field">
    <div class="m-4" >
      <%= f.label :price_Of_Product,class:"p-1" %>
      <%= f.number_field :price %>
    </div>
  </div>
  <div class="field">
    <div class="m-4" >
      <%= f.label :images_Of_Product,class:"p-1" %>
      <%= f.file_field :images, multiple: true %>
    </div>
  </div>
  
  <div class="field">
    <div class="m-4" >
        <%= f.label :Select_Catagory,class:"p-1" %>
        <%= select_tag('catagory', options_from_collection_for_select(Catagory.all, "id", "name"),
          { prompt: "Select A Category",class:"catagory" }) %> 
   </div>
  </div>

  <div class="field">
    <div class="m-4" >
      <div class='label'></div>
      <%= f.select :subcatagory_ids,'',{ prompt: 'select a Subcategory' },{:multiple => true, :size => 4,hidden: true,id:'select_subcatagory' } %>
    </div>
  </div>
  <div class="field">
    <div class="m-4" >
      <%= f.submit "Submit" %>
    </div>
  </div>

<% end %>

<script>
  $(document).ready(function () {
    $('.catagory').on('change', function() {
      var selected_value=$(this).val();
      console.log(selected_value);
      $("#select_subcatagory").removeAttr('hidden');
      $.ajax({
        type:"get",
        url:"/subcatagories/"+selected_value+"/get_subcategory"
      });

    });

  });

</script>

app/views/admin/products/edit.html.erb
 <h1>Update product</h1>


<div>
   <%= render 'form' %>
 </div>

app/views/admin/products/index.html.erb
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
<h1>All Products</h1>
<table id="product_datatable" class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Image</th>
      <th>Product Subcategory</th>
      <th>show</th>
      <th>edit</th>
      <th>remove</th>
    </tr>
  </thead> 
  <tbody>
    <% @products.each do |product| %>
      <tr class="table-info hover">
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <% if product.images.present? %>
         <td> <%= image_tag product.images[0].url ,style:'width: 30px; display: block' %></td>
        <% else %>
        <td>no image</td>
        <% end %>
        <td>
          <div class="dropdown">
            <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false" style='background:#F1F6F7;' >
              Product Subcategory
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <table class="table table-striped">
              <tr>
                <th>Name</th>
              </tr>
              <% product.subcatagories.each do |subcatagory| %>
              <tr class='table-info'>
                <td><li><%= subcatagory.name %></li></td>
              </tr>
              <% end %>
            </table>
            </ul>
          </div>
        </td>
        <td><%= link_to 'Show', admin_product_path(product) %></td>
        <td><%= link_to 'edit', edit_admin_product_path(product) %></td>
        <td><%= link_to 'remove', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>        
        
      </tr>
    <% end %>
  </tbody>

</table>

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>

<script>
  $(window).on('load', function() {
    var t = $('#product_datatable').DataTable();
      $("body").css("background-color","#5BB9B8");
  });
</script>

app/views/admin/products/new.html.erb
 <h1>New product</h1>


<div>
   <%= render 'form' %>
 </div>

app/views/admin/products/show.html.erb
<div claass='container' >
  <div class="row row-cols-2 row-cols-md-2 g-4 py-5 px-5" >
    <div class='col'>
      <% if @product.images.present? %>
        <%= image_tag @product.images[0].url ,style:'width:200px' %>
      <% end %>
    </div>
    <div>
      <div>
        <p><%= @product.name %></p>
      </div>
      <div>
        <p><%= @product.price %></p>
      </div>
      <div>
        <p><%= @product.user.first_name %></p>
      </div>
      
        <% @product.subcatagories.each do |subcatagory| %>
            <%= subcatagory.name %>
        <% end %>


    <div>
    </div>
  </div>
</div>